AAA/urls.py
from django.urls import path
from AAA.views import *

app_name='AAA'

urlpatterns=[
        path('alluarjun/',alluarjun,name='alluarjun')

]

project011/urls.py
from django.contrib import admin
from django.urls import path,include
import AAA,sneha

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AAA/',include('AAA.urls')),
    path('sneha/',include('sneha.urls')),

]

sneha/urls.py
from django.urls import path
from sneha.views import *

app_name='sneha'

urlpatterns=[
        path('snehareddy/',snehareddy,name='snehareddy')

]

AAA/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models

# Create your models here.

sneha/models.py
from django.db import models

# Create your models here.

AAA/views.py
from django.shortcuts import render

# Create your views here.



def alluarjun(request):
    return render(request,'alluarjun.html')

app/views.py
from django.shortcuts import render

# Create your views here.


def

sneha/views.py
from django.shortcuts import render

# Create your views here.

def snehareddy(request):
    return render(request,'snehareddy.html')

templates/alluarjun.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet"href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
    <h1>this is alluarjun page</h1>
    <h1><a href="{% url 'sneha:snehareddy' %}">navigate go to sneha</a></h1>
    <h1><img src="{% static 'images/allu.jpg' %}" alt="" srcset=""></h1>
    </center>
</body>
</html>

templates/snehareddy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <center>
        <h1>this is sneha page </h1>
        <h1><a href="{% url 'AAA:alluarjun' %}">navigate go to alluarjun</a></h1>
        <h1><img src="{% static 'images/allu2.jpg' %}" alt="" srcset=""></h1>

        </h1>
    </center>
</body>
</html>